#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr "NextGIS Geoinformationssystem"

#: __init__.py:219
msgid "Linux kernel"
msgstr "Linux-Kern"

#: __init__.py:222
msgid "OS distribution"
msgstr "Betriebssystemverteilung"

#: __init__.py:234
msgid "CPU"
msgstr "Zentralprozessor"

#: __init__.py:238
msgid "RAM"
msgstr "RAM"

#: exception.py:90
msgid "Validation error"
msgstr "Validierungsfehler"

#: exception.py:95
msgid "Forbidden"
msgstr ""

#: exception.py:100
msgid "Insufficient permissions"
msgstr "Berechtigungen nicht ausreichend"

#: exception.py:105
msgid "Operational error"
msgstr "Betriebsfehler"

#: exception.py:110
msgid "External service error"
msgstr ""

#: storage.py:222
msgid "Estimation is already running"
msgstr ""

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr "Die Antwort ist %d"

