#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr "Système d'information géographique (NextGIS)"

#: __init__.py:219
msgid "Linux kernel"
msgstr "Noyau Linux"

#: __init__.py:222
msgid "OS distribution"
msgstr "la distribution OS"

#: __init__.py:234
msgid "CPU"
msgstr "CPU"

#: __init__.py:238
msgid "RAM"
msgstr "RAM"

#: exception.py:90
msgid "Validation error"
msgstr "Erreur de validation"

#: exception.py:95
msgid "Forbidden"
msgstr ""

#: exception.py:100
msgid "Insufficient permissions"
msgstr "Permissions insuffisantes"

#: exception.py:105
msgid "Operational error"
msgstr "Erreur opérationnelle"

#: exception.py:110
msgid "External service error"
msgstr ""

#: storage.py:222
msgid "Estimation is already running"
msgstr "L'estimation est déjà en cours"

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr "La réponse est %d"

